/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.Factura.Factura;
import clases.Persona.Cliente;
import clases.Producto.Producto;
import clases.Util;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc_sistemas2020
 */
public class frmFactura extends javax.swing.JFrame {

    /**
     * Creates new form frmFactura
     */
    public frmFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtvendedorcod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtvendedordesc = new javax.swing.JTextField();
        txtcorrelativo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtclientedesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalle = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtigv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtproductocod = new javax.swing.JTextField();
        txtproductodesc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtproductocantidadventa = new javax.swing.JTextField();
        btnbuscarproducto = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtpreciounitario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtclientecod = new javax.swing.JTextField();
        btnbuscarcliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txttipodocumento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtImporteLetras = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Serie");

        jLabel2.setText("Fecha");

        jLabel3.setText("Vendedor");

        jLabel4.setText("Cliente");

        tabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalle);

        jLabel7.setText("Subtotal");

        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("IGV");

        txtigv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Descuento");

        txtdescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("Total");

        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Producto");

        txtproductocod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtproductocodFocusLost(evt);
            }
        });
        txtproductocod.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtproductocodPropertyChange(evt);
            }
        });
        txtproductocod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproductocodKeyTyped(evt);
            }
        });

        jLabel11.setText("Cantidad");

        btnbuscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_15px.png"))); // NOI18N
        btnbuscarproducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_15px.png"))); // NOI18N
        btnbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproductoActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar_15px.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retirar_15px.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel13.setText("Stock");

        txtstock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstockFocusLost(evt);
            }
        });
        txtstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstockActionPerformed(evt);
            }
        });
        txtstock.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtstockPropertyChange(evt);
            }
        });
        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstockKeyTyped(evt);
            }
        });

        jLabel15.setText("Precio unitario");

        txtpreciounitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpreciounitarioFocusLost(evt);
            }
        });
        txtpreciounitario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpreciounitarioPropertyChange(evt);
            }
        });
        txtpreciounitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpreciounitarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtproductocod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtproductodesc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpreciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscarproducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtproductocantidadventa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEliminar)
                        .addComponent(btnAgregar))
                    .addComponent(btnbuscarproducto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtproductocod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtproductodesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtproductocantidadventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtpreciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)))
        );

        jLabel14.setText("Correlativo");

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NuevoDocumento_48px.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_48px.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnbuscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_15px.png"))); // NOI18N
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Documento");

        jLabel12.setText("Son:");

        txtImporteLetras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImporteLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsubtotal)
                            .addComponent(txtigv)
                            .addComponent(txtdescuento)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvendedorcod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcorrelativo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                            .addComponent(txtvendedordesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtclientecod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtclientedesc)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscarcliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttipodocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtcorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel5)
                            .addComponent(txttipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtvendedorcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtvendedordesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtclientedesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtclientecod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnbuscarcliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImporteLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        Guardar();
        HabilitarControl(false);
        LimpiarControles();
        btnnuevo.setEnabled(true);
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Se guardo el documento");
        
    }//GEN-LAST:event_btnguardarActionPerformed
    
    private void Guardar(){
        String contenidoCabecera ="C"+"|"+ txtserie.getText().trim() + "|"+ txtcorrelativo.getText().trim() + "|" + 
                txtclientecod.getText() + "|" + txtclientedesc.getText() +"|" + 
                txtvendedorcod.getText() + "|" + txtvendedordesc.getText() + "|" +
                txtFecha.getText() + "|" + txtigv.getText() + "|" +
                txtsubtotal.getText() + "|" + txttotal.getText() +"\n";
        String rutaArchivo = "C:\\Users\\pc_sistemas2020\\OneDrive\\Documentos\\NetBeansProjects\\Basedatos.txt";
        Util.Escribir(rutaArchivo, contenidoCabecera);
        
        //Detalle
        String contenidoDetalle = "";
        for(int x = 0; x < tabladetalle.getRowCount();x++){
            
             contenidoDetalle = "D" +"|" + txtserie.getText().trim() + "|"+ txtcorrelativo.getText().trim() + "|" +
                                tabladetalle.getValueAt(x, 0) + "|" + tabladetalle.getValueAt(x, 1)+"|"+ 
                                tabladetalle.getValueAt(x, 2) + "|" + tabladetalle.getValueAt(x, 3) +"|"+ 
                                tabladetalle.getValueAt(x, 4)+"\n";
             Util.Escribir(rutaArchivo, contenidoDetalle);
                     
        }
        
        
        
    }
    private void LimpiarControles(){
        txtserie.setText("");
        txtcorrelativo.setText("");
        txtFecha.setText("");
        txttipodocumento.setText("");
        
        txtclientecod.setText("");
        txtclientedesc.setText("");
        btnbuscarcliente.setText("");
        
        txtproductocod.setText("");
        txtproductodesc.setText("");
        btnbuscarproducto.setText("");
        txtproductocantidadventa.setText("");
        txtstock.setText("");
        txtpreciounitario.setText("");
        btnAgregar.setText("");
        btnEliminar.setText("");
        
        txtvendedorcod.setText("");
        txtvendedordesc.setText("");
        
        txtigv.setText("");
        txtdescuento.setText("");
        txttotal.setText("");
        txtImporteLetras.setText("");
        txtsubtotal.setText("");
        
        
    }
    private void HabilitarControl(boolean  estado){
        txtserie.setEditable(false);
        txtcorrelativo.setEditable(false);
        txtFecha.setEditable(false);
        txttipodocumento.setEditable(false);
        
        txtclientecod.setEditable(estado);
        txtclientedesc.setEditable(false);
        btnbuscarcliente.setEnabled(estado);
        
        txtproductocod.setEditable(estado);
        txtproductodesc.setEditable(false);
        btnbuscarproducto.setEnabled(estado);
        txtproductocantidadventa.setEnabled(estado);
        txtstock.setEditable(false);
        txtpreciounitario.setEditable(false);
        btnAgregar.setEnabled(estado);
        btnEliminar.setEnabled(estado);
        
        txtvendedorcod.setEditable(false);
        txtvendedordesc.setEditable(false);
        
        txtigv.setEditable(false);
        txtdescuento.setEditable(false);
        txttotal.setEditable(false);
        txtImporteLetras.setEditable(false);
        txtsubtotal.setEditable(false);
        AsignarColorControlporEstado();
        DefaultTableModel modelo = (DefaultTableModel)this.tabladetalle.getModel();
        modelo.setRowCount(0);
    }
    private void CargarValoresPorDefecto(){
        txtvendedorcod.setText("E0001");
        txtvendedordesc.setText("Manuel Perez");
        Date fechActual = new Date(2022, 5, 15);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaTexto = sdf.format(fechActual);        
        txtFecha.setText(fechaTexto);
        txttipodocumento.setText("FACTURA");
    }
    Factura f = new Factura();
    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        LimpiarControles();
        HabilitarControl(true);
        HabilitarBotonesMantenimiento(true);
        txtserie.setText(f.generarSerie()); 
        txtcorrelativo.setText(f.generarCorrelativo());
        
        
        
        
        CargarValoresPorDefecto();        
        
        
        
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        HabilitarControl(false);
        LimpiarControles();
        HabilitarBotonesMantenimiento(false);
        
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtproductocodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductocodKeyTyped
        
    }//GEN-LAST:event_txtproductocodKeyTyped

    private void txtproductocodPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtproductocodPropertyChange
         
    }//GEN-LAST:event_txtproductocodPropertyChange

    private void txtproductocodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproductocodFocusLost
      
        /*String codigo  = txtproductocod.getText();
        Producto p = new Producto();
           
        
        if(codigo.isEmpty() == false){
           String codprod = p.Buscar(codigo)[0];
           String desprod  = p.Buscar(codigo)[1];
           double stock = Double.parseDouble(p.Buscar(codigo)[2]) ;
           double precio = Double.parseDouble(p.Buscar(codigo)[3]);
           
           txtproductocod.setText(codprod);
           txtproductodesc.setText(desprod);
           
                   
        }
        */
    }//GEN-LAST:event_txtproductocodFocusLost

    private void btnbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproductoActionPerformed
                        
       try {
            String codigo  = txtproductocod.getText().trim();
            Producto p = new Producto();
            System.out.println("paso instancia de producto");
            
            if(codigo.isEmpty() == false){
                String[] resultado = p.Buscar(codigo);
               String codprod = resultado[0];
               String desprod  = resultado[1];

               

               double stock = Double.parseDouble(resultado[2]) ;
               double precio = Double.parseDouble(resultado[3]);

               txtproductocod.setText(codprod);
               txtproductodesc.setText(desprod);     
               txtstock.setText(String.valueOf(stock));
               txtpreciounitario.setText(String.valueOf(precio));
               
            }
        
       } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
       }
       
    }//GEN-LAST:event_btnbuscarproductoActionPerformed
    private void FormatearColorControl(JTextField control){
        if(control.isEditable()== false){
            control.setBackground(Color.lightGray);            
        }else{
            control.setBackground(Color.white);
        }
    }
    private void FormatearColorControl(JFormattedTextField control){
        
        if(control.isEditable()== false){
            control.setBackground(Color.lightGray);            
        }else{
            control.setBackground(Color.white);
        }
    }
    private void AsignarColorControlporEstado(){
        FormatearColorControl(txtFecha);
        FormatearColorControl(txttipodocumento);
        
        FormatearColorControl(txtserie);
        FormatearColorControl(txtcorrelativo);
        
        FormatearColorControl(txtclientecod);
        FormatearColorControl(txtclientedesc);
        FormatearColorControl(txtFecha);
        FormatearColorControl(txtFecha);
        FormatearColorControl(txtproductocod);
        FormatearColorControl(txtproductodesc);
        FormatearColorControl(txtproductocantidadventa);
        FormatearColorControl(txtstock);
        FormatearColorControl(txtpreciounitario);
        FormatearColorControl(txtvendedorcod);
        FormatearColorControl(txtvendedordesc);
                        
        FormatearColorControl(txtigv);
        FormatearColorControl(txtdescuento);
        FormatearColorControl(txttotal);
        FormatearColorControl(txtImporteLetras);
        FormatearColorControl(txtsubtotal);
    }
    private void HabilitarBotonesMantenimiento(boolean estado)
    {
        btnnuevo.setEnabled(!estado);
        btnAgregar.setEnabled(estado);
        btnEliminar.setEnabled(estado);
        btncancelar.setEnabled(estado);
        btnguardar.setEnabled(estado);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        HabilitarBotonesMantenimiento(false);
        HabilitarControl(false);
        //grilla
//        String[] columnas = new String[4];
//        
//        columnas[0] = "Descripcion";
//        columnas[1] = "Cantidad";
//        columnas[2] = "Precio";
//        columnas[3] = "Importe";
        
        DefaultTableModel modelo = (DefaultTableModel)this.tabladetalle.getModel();
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Importe");
        modelo.setRowCount(0);
                
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //habilitarControl(false);
    }//GEN-LAST:event_formWindowActivated

    private void txtstockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstockFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockFocusLost

    private void txtstockPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtstockPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockPropertyChange

    private void txtstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockKeyTyped

    private void txtpreciounitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpreciounitarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreciounitarioFocusLost

    private void txtpreciounitarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpreciounitarioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreciounitarioPropertyChange

    private void txtpreciounitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciounitarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreciounitarioKeyTyped

    private void txtstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
//        String[] columnas = new String[4];
//        
//        columnas[0] = "Descripcion";
//        columnas[1] = "Cantidad";
//        columnas[2] = "Precio";
//        columnas[3] = "Importe";
//        
//        DefaultTableModel modelo = (DefaultTableModel)this.tabladetalle.getModel();
//        modelo.addColumn(columnas);
        //codigo
        //descripcion
        //cantiddad
        //precio
        //importe
        int indice = 0;
        DefaultTableModel modelo = (DefaultTableModel)this.tabladetalle.getModel();
        String codigo, descripcion;
        double cantidad = 0, precio = 0, importe = 0;
        codigo = txtproductocod.getText().trim();
        descripcion = txtproductodesc.getText().trim();
        cantidad = Integer.parseInt(txtproductocantidadventa.getText().trim());
        precio = Double.parseDouble(txtpreciounitario.getText().trim());
        importe = cantidad * precio;
        Object[] datos = new Object[5];
        datos[0] = codigo;
        datos[1] = descripcion;
        datos[2] = cantidad;
        datos[3] = precio;
        datos[4] = importe;
        
        //if(modelo.getRowCount() )
        
        modelo.addRow(datos);
        
        /*
        int filaActual = modelo.getRowCount();
            for(int x = 0; x < modelo.getColumnCount();x++){
                modelo.setValueAt(datos[x], filaActual, x);                              
            }
          */  
            
        
        calcular();
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed
    private void calcular(){
        
        double  subtotal=0;
        //leo total de fila
        
        int cantidadFilas=tabladetalle.getRowCount();
//        System.out.println("Cantidad de filas:" + cantidadFilas);
//        System.out.println(tabladetalle.getValueAt(0, 1));
//        System.out.println(tabladetalle.getValueAt(0, 4));
        
        for (int I=0;I<=cantidadFilas-1;I++){
            //recorriendo cada fila para realizar la suma del subtotal por fila insertada
            System.out.println("Fila actual:" +I );
            Double valorCelda = Double.parseDouble(String.valueOf(tabladetalle.getValueAt(I, 4)));

            
            //Double valorCelda = Double.parseDouble((String)tabladetalle.getValueAt(I, 4));
            //System.out.println("Valor celda:" + valorCelda);
            subtotal=subtotal+valorCelda;
            
        }
        
        double igv = 0.18 *  subtotal;
        double total = subtotal  + igv;
        txtsubtotal.setText(String.valueOf(subtotal));
        txtigv.setText(String.valueOf(igv));
        txttotal.setText(String.valueOf(total));
        
    }
    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
        
        String codigo = txtclientecod.getText().trim();
        Cliente c = new Cliente();

            if(codigo.isEmpty() == false){
                
                String[] resultado = c.Buscar(codigo);
                
               String codigocliente = resultado[0];
               String descripcionclente  = resultado[1];
              
               txtclientecod.setText(codigocliente);
               txtclientedesc.setText(descripcionclente);                              
            }
        
        
        
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.tabladetalle.getModel();        
        
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea eliminar el registro");
        if(respuesta == 0){
            //confirma eliminar
            modelo.removeRow(tabladetalle.getSelectedRow());
        }
        calcular();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarproducto;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladetalle;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtImporteLetras;
    private javax.swing.JTextField txtclientecod;
    private javax.swing.JTextField txtclientedesc;
    private javax.swing.JTextField txtcorrelativo;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtpreciounitario;
    private javax.swing.JTextField txtproductocantidadventa;
    private javax.swing.JTextField txtproductocod;
    private javax.swing.JTextField txtproductodesc;
    private javax.swing.JTextField txtserie;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttipodocumento;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvendedorcod;
    private javax.swing.JTextField txtvendedordesc;
    // End of variables declaration//GEN-END:variables
}
